[package]
name = "snappy"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "4.0"
actix-files = "0.6"
env_logger = "0.9"
log = "0.4"

[dev-dependencies]
actix-rt = "2.2"
